apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-scanner
  namespace: security-scanner
subjects:
- kind: ServiceAccount
  name: security-scanner
  namespace: security-scanner
roleRef:
  kind: ClusterRole 
  name: security-scanner
  apiGroup: rbac.authorization.k8s.io