apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-scanner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: >-
      https://ifs-security-scanner@dev.azure.com/ifs-security-scanner/Security-Scanner/_git/security-scanner
    path: security-scanner
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security-scanner
  syncPolicy:
    automated:
      prune: true
