apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-scanner-clair-postgres
  name: postgres-svc
  namespace: security-scanner
spec:
  ports:
    - port: 5432
  selector:
    app: security-scanner-clair-postgres