apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: security-scanner-clair-postgres
  name: security-scanner-clair-postgres
  namespace: security-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-scanner-clair-postgres
  template:
    metadata:
      labels:
        app: security-scanner-clair-postgres
    spec:
      containers:
      - image: postgres:latest
        imagePullPolicy: Always
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
          name: postgres-port
      serviceAccountName: security-scanner  
---