apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-scanner-postgres-pvc
  namespace: security-scanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      
  