apiVersion: v1
kind: Service
metadata:
  name: clair-svc
  namespace: security-scanner
  labels:
    app: security-scanner-clair
spec:
  type: ClusterIP
  ports:
  - port: 6060
    targetPort: 6060
    protocol: TCP
    name: clair-server-port
  - port: 6061
    targetPort: 6061
    protocol: TCP
    name: clair-health-port
  selector:
    app: security-scanner-clair
---