
apiVersion: batch/v1
kind: Job
metadata:
  name: security-scanner-sysdig
  namespace: security-scanner
  labels:
    app: security-scanner-sysdig
spec:
  # parallelism: 1    
  # completions: 1    
  # activeDeadlineSeconds: 60
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: security-scanner-sysdig
    spec:
      containers:
        - name: security-scanner-sysdig
          image: rnddockerdev.azurecr.io/ifs/security-scanner-sysdig
          imagePullPolicy: Always
          env:
          - name: COMMAND
            value: "COMMAND_PLACEHOLDER"
          - name: SCANSECONDS
            value: "SCANSECONDS_PLACEHOLDER"
          volumeMounts:
          - mountPath: /host/dev         
            name: dev-volume
          - mountPath: /host/proc
            name: proc-volume
          - mountPath: /host/boot
            name: boot-volume
          - mountPath: /host/lib/modules
            name: lib-volume
          - mountPath: /host/usr
            name: usr-volume
          securityContext:
            privileged: true
      volumes:
        - name: dev-volume
          hostPath:
            path: /dev
        - name: proc-volume
          hostPath:
            path: /proc
        - name: boot-volume
          hostPath:
            path: /boot
        - name:  lib-volume
          hostPath:
            path: /lib/modules
        - name: usr-volume
          hostPath:
            path: /usr 
      restartPolicy: Never 
      imagePullSecrets:
         - name: regcred  
      serviceAccountName: security-scanner    

