apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: security-scanner-falcosidekick
  name: security-scanner-falcosidekick
  namespace: security-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-scanner-falcosidekick
  template:
    metadata:
      labels:
        app: security-scanner-falcosidekick
    spec:
      containers:
      - image: falcosecurity/falcosidekick
        imagePullPolicy: Always
        name: security-scanner-falcosidekick
        env:
        - name: TEAMS_WEBHOOKURL
          value: TEAMS_WEBHOOKURL_PLACEHOLDER
       - name: TEAMS_OUTPUTFORMAT
          value: all
        - name: TEAMS_MINIMUMPRIORITY
          value: debug
        ports:
        - containerPort: 2801
      serviceAccountName: security-scanner  
