apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-scanner-falcosidekick
  name: falcosidekick-svc
  namespace: security-scanner
spec:
  ports:
    - port: 2801
      targetPort: 2801
  selector:
    app: security-scanner-falcosidekick