apiVersion: batch/v1
kind: Job
metadata:
  name: security-scanner-trivy
  namespace: security-scanner
  labels:
    app: security-scanner-trivy
spec:
  template:
    metadata:
      labels:
        app: security-scanner-trivy
    spec:
      containers:
        - name: security-scanner-trivy
          image: rnddockerdev.azurecr.io/ifs/security-scanner-trivy
          imagePullPolicy: Always
          env:
          - name: COMMAND
            value: COMMAND_PLACEHOLDER
          - name: TRIVY_USERNAME
            value: REGISTRYUSERNAME_PLACEHOLDER
          - name: TRIVY_PASSWORD
            value: REGISTRYPASSWORD_PLACEHOLDER
      restartPolicy: Never 
      imagePullSecrets:
        - name: regcred 
      serviceAccountName: security-scanner     

